Output demo.gif

Set Shell "bash"
Set FontSize 13
Set Width 1000
Set Height 750
Set Theme "Dracula"
Set Padding 10

Type "./tcal"
Enter
Sleep 1s

# gezinme
Type "lll"
Sleep 600ms
Type "hh"
Sleep 600ms

# gorev ekle: :e
Type ":e"
Enter
Sleep 500ms
Type "Dis randevusu"
Sleep 300ms
Enter
Sleep 800ms

Type ":e"
Enter
Sleep 500ms
Type "Rapor teslim"
Sleep 300ms
Enter
Sleep 1s

# gorev secimine gir (j ile)
Type "j"
Sleep 600ms
Type "j"
Sleep 600ms
Type "k"
Sleep 600ms

# ay degistir
Type "n"
Sleep 1s
Type "p"
Sleep 1s

# secili gorevi sil: :d
Type "j"
Sleep 500ms
Type ":d"
Enter
Sleep 1s

# cikis
Type ":q"
Enter
Sleep 500ms
